services:
  uptime-kuma:
    image: louislam/uptime-kuma:28.1.0
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - /mnt/docker-data/uptime-kuma:/app/data
